[workspace]
solana_version = "2.2.14"

[features]
seeds = false    # disable automatic PDA generation via seeds
skip-lint = false # enable code linting checks

[programs.localnet]
# Mapping for localnet cluster
cyberia_program = "HaesmfbnNYXgL7JGEPuAEPuAZcmELoHrHA355i5TSNui"

[programs.devnet]
# ID do programa após deploy em Devnet
cyberia_program = "HGQrWdDDiusDYaW33YCenNmDJtJkXG5kn2eHaj3cgntf"

[registry]
# IDL registry endpoint (optional)
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "${WALLET_PATH}"

[scripts]
# Custom scripts for Anchor CLI
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
# time (in milliseconds) to wait for the local validator to start
startup_wait = 15000

[toolchain]
anchor_version = "0.31.1"
