[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
cyberia_program = "HaesmfbnNYXgL7JGEPuAEPuAZcmELoHrHA355i5T5Nui"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet  = "target/test-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
