[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
cyberia_template = "HaesmfbnNYXgL7JGEPuAEPuAZcmELoHrHA355i5T5Nui"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/masqual/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
