[workspace]
members = [
    "programs/*"
]
resolver = "2"

[profile.release]
overflow-checks = true

[workspace.dependencies]
solana-program = "=2.1.0"
solana-pubkey = "=2.1.0"
solana-msg = "=2.1.0"
solana-sha256 = "=2.1.0"