# CI/CD pipeline: build, test and deploy Anchor program to Solana Devnet
# Local: .github/workflows/deploy-devnet.yml

name: CI/CD Solana Devnet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Instalar Solana CLI v1.16.5
        run: |
          curl -sSfL https://release.solana.com/v1.16.5/install | sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Instalar Anchor CLI
        run: npm install -g @project-serum/anchor-cli

      - name: Compilar programa Anchor
        working-directory: program
        run: anchor build

      - name: Executar testes
        working-directory: programs/cyberia
        run: anchor test --skip-deploy

  deploy:
    if: github.event_name == 'push'
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Solana CLI no PATH
        run: echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Definir keypair (segredo)
        env:
          SOLANA_KEYPAIR: ${{ secrets.SOLANA_KEYPAIR_JSON }}
        run: |
          echo "$SOLANA_KEYPAIR" > keypair.json
          solana config set --keypair keypair.json

      - name: Configurar Anchor para Devnet
        run: |
          anchor config set cluster devnet
          anchor config set wallet keypair.json

      - name: Deploy na Devnet
        working-directory: programs/cyberia
        run: anchor deploy

