# CI/CD pipeline: build, test and deploy Anchor program na Solana Devnet
# Local: .github/workflows/deploy-devnet.yml

name: CI/CD Solana Devnet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências JS
        run: npm ci

      - name: Checar formatação JS/TS (Prettier)
        run: npm run lint

      # → 2) Setup Rust + Anchor como antes
      - name: Instalar Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Instalar Solana CLI v1.16.5
        run: |
          curl -sSfL https://release.solana.com/v1.16.5/install | sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Instalar Anchor CLI
        run: npm install -g @project-serum/anchor-cli

      # → 3) Checagem de formatação Rust/Anchor
      - name: Checar formatação Rust (cargo fmt)
        run: cargo fmt -- --check

      - name: Checar formatação Anchor (anchor fmt)
        run: anchor fmt -- --check

      # → 4) Lint adicional em Rust
      - name: Lint Rust (clippy)
        run: cargo clippy --all-targets --all-features -- -D warnings

      # → 5) Seu build e testes atuais
      - name: Compilar programa Anchor
        working-directory: programs/cyberia_program
        run: anchor build

      - name: Executar testes
        working-directory: programs/cyberia_program
        run: anchor test --skip-deploy

  deploy:
    if: github.event_name == 'push'
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Solana CLI v1.16.5
        run: |
          curl -sSfL https://release.solana.com/v1.16.5/install | sh
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Instalar Anchor CLI
        run: npm install -g @project-serum/anchor-cli

      - name: Definir keypair (segredo)
        env:
          SOLANA_KEYPAIR: ${{ secrets.SOLANA_KEYPAIR_JSON }}
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          echo "$SOLANA_KEYPAIR" > keypair.json
          solana config set --keypair keypair.json

      - name: Configurar Anchor para Devnet
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          anchor config set cluster devnet
          anchor config set wallet keypair.json

      - name: Deploy na Devnet
        working-directory: programs/cyberia_program
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          anchor deploy
