name: Deploy Devnet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # 2) Node.js + Prettier
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install JS dependencies
        run: npm ci

      - name: Check JS/TS formatting (Prettier)
        run: npm run lint

      # 3) Rust toolchain
      - name: Instalar Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # 4) Solana & Anchor
      - name: Install Solana CLI
        run: |
          curl -sSfL https://release.solana.com/v1.16.5/install | sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install Anchor CLI
        run: npm install -g @project-serum/anchor-cli

      # 5) Formatação Rust/Anchor e lint
      - name: Check Rust formatting (cargo fmt)
        run: cargo fmt -- --check

      - name: Check Anchor formatting (anchor fmt)
        run: anchor fmt -- --check

      - name: Lint Rust (clippy)
        run: cargo clippy --all-targets --all-features -- -D warnings

      # 6) Build & Test
      - name: Compilar programa Anchor
        working-directory: programs/cyberia_program
        run: anchor build

      - name: Executar testes
        working-directory: programs/cyberia_program
        run: anchor test --skip-deploy

  deploy:
    if: github.event_name == 'push'
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Solana CLI v1.16.5
        run: |
          curl -sSfL https://release.solana.com/v1.16.5/install | sh
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Instalar Anchor CLI
        run: npm install -g @project-serum/anchor-cli

      - name: Definir keypair (segredo)
        env:
          SOLANA_KEYPAIR: ${{ secrets.SOLANA_KEYPAIR_JSON }}
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          echo "$SOLANA_KEYPAIR" > keypair.json
          solana config set --keypair keypair.json

      - name: Configurar Anchor para Devnet
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          anchor config set cluster devnet
          anchor config set wallet keypair.json

      - name: Deploy na Devnet
        working-directory: programs/cyberia_program
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          anchor deploy
